pub mod callback_query;
pub mod chat;
pub mod chat_invite_link;
pub mod chat_member;
pub mod chat_member_update;
pub mod chosen_inline_result;
pub mod forum_topic_created;
pub mod inline_query;
pub mod inline_query_result;
pub mod input_file;
pub mod message;
pub mod pre_checkout_query;
pub mod primitive;
pub mod refs;
pub mod reply_markup;
pub mod response_parameters;
pub mod shipping_query;
pub mod text;
pub mod update;
//-------------------------------------
pub mod chat_administrator;
mod chat_boost;
mod chat_boost_removed;
mod input_file_x;
mod input_media;
mod link_preview_options;

pub use input_file_x::*;

pub use input_media::*;

pub use self::callback_query::*;
pub use self::link_preview_options::*;
pub use self::chat::*;
pub use self::chat_administrator::*;
pub use self::chat_invite_link::*;
pub use self::chat_member::*;
pub use self::chat_member_update::*;
pub use self::chosen_inline_result::*;
pub use self::forum_topic_created::*;
pub use self::inline_query::*;
pub use self::inline_query_result::*;
pub use self::input_file::*;
pub use self::message::*;
pub use self::pre_checkout_query::*;
pub use self::primitive::*;
pub use self::refs::*;
pub use self::reply_markup::*;
pub use self::response_parameters::*;
pub use self::shipping_query::*;
pub use self::text::*;
pub use self::update::*;
